import { useState } from 'react'
import queueFixtures from '../../data/forecast-review.json'
import seasonal from '../../data/seasonal-detail.json'
import './ExceptionDetails.css'

function DemandChart() {
  const points = field => seasonal.demandSeries.map((d,i)=>`${80+i*200},${165-d[field]*1.1}`).join(' ')
  return <figure className="ed-chart"><figcaption>Forecast vs Actual Demand <span>Representative product series · demand index</span></figcaption><div className="ed-legend"><span><i className="forecast"/>Forecast</span><span><i className="actual"/>Actual demand</span></div><svg viewBox="0 0 560 205" role="img" aria-label="Actual demand rises from 100 to 110 to 120; forecast rises from 94 to 99 to 102 over three cycles.">{[0,40,80,120].map(value=><g key={value}><line x1="45" x2="525" y1={165-value*1.1} y2={165-value*1.1} stroke="#e2e8f0"/><text x="32" y={169-value*1.1} textAnchor="end">{value}</text></g>)}<polyline points={points('actual')} fill="none" stroke="#188563" strokeWidth="3"/><polyline points={points('forecast')} fill="none" stroke="#315cd7" strokeWidth="3" strokeDasharray="7 4"/>{seasonal.demandSeries.map((d,i)=><g key={d.label}><circle cx={80+i*200} cy={165-d.actual*1.1} r="4" fill="#188563"/><circle cx={80+i*200} cy={165-d.forecast*1.1} r="4" fill="#315cd7"/><text x={80+i*200} y="193" textAnchor="middle">{d.label}</text></g>)}</svg></figure>
}
function PageHeader({priority,onBack}) {
 return <><button className="detail-back" onClick={onBack}>← Back to Forecast Review</button><header className="ed-header"><span className="fl-eyebrow">FORECASTING AGENT</span><div><h1>Exception Details</h1><span className={`ed-priority ${priority==='Low'?'ed-low':''}`}>{priority} Priority</span></div><p>A detailed view of the agent’s diagnosis and recommended action.</p></header></>
}
function SectionTitle({number,children}) {return <h2 className="ed-section-title"><span>{number}</span>{children}</h2>}
export default function ExceptionDetails({exception:e,cycleData,onBack,onPrecedent}) {
 const [decision,setDecision]=useState(null)
 const [escalation,setEscalation]=useState(false)
 const client=cycleData.cycle.client_id
 const q=queueFixtures[client].issues[e.id]
 const flagship=client==='VELORA'&&e.id==='exc-2'
 const percent=(q.affectedSkus/cycleData.cycle.skus_scanned*100).toFixed(1)
 const p=e.planner
 if(!flagship) return <article className="exception-page"><PageHeader priority={q.priority} onBack={onBack}/><section className="ed-issue"><h2>{p.issue}</h2><p>{p.impact}</p><dl className="ed-facts"><div><dt>Affected SKUs</dt><dd>{q.affectedSkus.toLocaleString()}</dd></div><div><dt>Product group</dt><dd>{e.segment}</dd></div><div><dt>Current status</dt><dd>{q.status}</dd></div><div><dt>Last updated</dt><dd>{q.updated}</dd></div></dl></section><section className="ed-section"><SectionTitle number="1">What happened?</SectionTitle><p>{p.happened}</p><ul>{p.evidence.map(item=><li key={item}>{item}</li>)}</ul></section><section className="ed-section"><SectionTitle number="2">Root-cause diagnosis</SectionTitle><p>{p.diagnosis}</p><p className="ed-confidence">Agent confidence: {e.rca.confidence}%</p></section><section className="ed-section"><SectionTitle number="3">Recommended intervention</SectionTitle><h3>{p.nextAction}</h3><p>{p.recommendation}</p></section><section className="ed-section"><SectionTitle number="4">Action & approval</SectionTitle><p>{p.approval}</p><span className="ed-status">{q.status}</span></section><section className="ed-section"><SectionTitle number="5">Historical precedent</SectionTitle><p>{e.rag.chunks[0].preview}</p><button className="ed-secondary" onClick={onPrecedent}>View full precedent →</button></section></article>
 return <article className="exception-page"><PageHeader priority="High" onBack={onBack}/>
   <section className="ed-issue"><h2>Seasonal demand is being under-forecast</h2><p>Underforecasting may leave plans short of demand.</p><dl className="ed-facts"><div><dt>Affected SKUs</dt><dd>{q.affectedSkus.toLocaleString()}</dd></div><div><dt>Percent of total</dt><dd>{percent}% <small>of {cycleData.cycle.skus_scanned.toLocaleString()} SKUs</small></dd></div><div><dt>Product group</dt><dd>{e.segment}</dd></div><div><dt>Current status</dt><dd><span className="ed-status">Awaiting DS approval</span></dd></div><div><dt>Last updated</dt><dd>Apr 24, 2026</dd></div></dl></section>
   <section className="ed-section"><SectionTitle number="1">What happened?</SectionTitle><p>Forecast accuracy has declined over the last three cycles, with consistent underforecasting.</p><div className="ed-metrics">{seasonal.metrics.map(m=><div key={m.label}><strong>{m.wmape}% <small>wMAPE</small></strong><span>{m.label}</span></div>)}<div className="ed-bias"><strong>+15%</strong><span>Underforecast bias</span></div></div><DemandChart/><p className="ed-impact">Planning may under-position inventory against expected demand.</p></section>
   <section className="ed-section"><SectionTitle number="2">Root-cause diagnosis</SectionTitle><p>The agent analyzed multiple potential causes in a structured sequence and identified the root cause.</p><div className="ed-table-wrap"><table className="ed-rca"><thead><tr><th>Step</th><th>Check</th><th>What the agent found</th><th>Conclusion</th></tr></thead><tbody>{seasonal.checks.map((check,i)=><tr key={check.check} className={check.root?'ed-root-row':''}><td>{i+1}</td><td>{check.check}</td><td>{check.finding}</td><td>{check.root&&<span className="ed-root-label">Root cause</span>}{check.conclusion}</td></tr>)}</tbody></table></div><div className="ed-diagnosis"><h3>Diagnosis</h3><p>{seasonal.diagnosis}</p><div className="ed-confidence"><span>Agent confidence: <strong>88%</strong></span><span>Root cause category: <strong>Feature drift</strong></span></div></div></section>
   <section className="ed-section"><SectionTitle number="3">Recommended intervention</SectionTitle><div className="ed-recommendation"><h3>Retrain the model</h3><p>Updating the seasonal demand feature and retraining the model addresses the structural issue rather than masking it with a temporary adjustment.</p></div><h3 className="ed-subheading">Why retrain instead of a temporary override?</h3><ul>{seasonal.reasons.map(reason=><li key={reason}>{reason}</li>)}</ul><dl className="ed-retrain-facts"><div><dt>Model</dt><dd>{seasonal.model}</dd></div><div><dt>Feature to refresh</dt><dd>{seasonal.feature}</dd></div><div><dt>Training window</dt><dd>{seasonal.trainingMonths} months</dd></div><div><dt>Affected SKUs</dt><dd>{q.affectedSkus.toLocaleString()}</dd></div><div><dt>Expected outcome</dt><dd>Improved seasonal forecast accuracy</dd></div><div><dt>Confidence</dt><dd>88%</dd></div></dl></section>
   <section className="ed-section"><SectionTitle number="4">Action & approval</SectionTitle><p>This recommendation requires human approval before it can be executed.</p><div className="ed-approval"><span className="ed-tier">Tier 2 — Recommend + approve</span><h3>Model retrain</h3><p><strong>Status:</strong> Awaiting Data Scientist approval</p><div className="ed-buttons"><button className="ed-primary" onClick={()=>setDecision('Approval selected')}>Approve retrain</button><button className="ed-reject" onClick={()=>setDecision('Rejection selected')}>Reject</button><button className="ed-secondary" onClick={()=>setDecision('Change request selected')}>Request changes</button></div><p className="ed-preview-note">Decision preview only. Nothing is saved or executed; selections reset when you leave this page.</p><div className="ed-feedback" role="status" aria-live="polite">{decision&&`${decision} for model retrain. Preview only.`}</div></div><div className="ed-escalation"><span className="ed-tier">Tier 3 — Expert escalation</span><h3>Feature refresh ownership</h3><p>Agree who owns recurring feature refreshes and future model changes. This recurring issue merits a tracked decision.</p><button className="ed-secondary" onClick={()=>setEscalation(true)}>Create escalation</button><div className="ed-feedback" role="status" aria-live="polite">{escalation&&'Escalation preview: feature refresh ownership. No ticket has been created.'}</div></div></section>
   <section className="ed-section"><SectionTitle number="5">Historical precedent</SectionTitle><p>The agent retrieved a similar past incident to inform this recommendation.</p><dl className="ed-precedent"><div><dt>Prior case</dt><dd>{seasonal.precedent.id}</dd></div><div><dt>Issue</dt><dd>{seasonal.precedent.issue}</dd></div><div><dt>Resolution</dt><dd>{seasonal.precedent.resolution}</dd></div><div><dt>Outcome</dt><dd>{seasonal.precedent.outcome}</dd></div></dl><button className="ed-secondary" onClick={onPrecedent}>View full precedent →</button></section>
 </article>
}
